### ISSUE TITLE
Баг в переносе придыхания при удвоении дезидератива

### ISSUE THREAD

**Issue by Marc-Winner** [anshir-rus/Anshir-Sanscrit-Verbs#1]
В некоторые примерах придыхание переносится (см. правило 34 Эмено) на удвоительный слог, вместо корня.

Некоторые примеры:
- [duh](http://sanskrit.anshir.ru/forms.php?id=454&final=pr): dhudukṣati vs. dudhukṣati ([Wh.](http://www.warnemyr.com/skrgram/grammar/roots/root_duh.html); Bucknell p. 171)
- [dah](http://sanskrit.anshir.ru/forms.php?id=63&final=pr): dhidakṣati vs. didhakṣati ([Wh.](http://www.warnemyr.com/skrgram/grammar/roots/root_dah.html); Bucknell p. 170)
- [dih](http://www.warnemyr.com/skrgram/grammar/roots/root_dih.html): dhidikṣati vs. didhikṣati ([Wh.](http://www.warnemyr.com/skrgram/grammar/roots/root_dih.html); Bucknell p. 171)
- [bandh](http://sanskrit.anshir.ru/forms.php?id=779&final=pr): bhibantsati vs. bibhantsati ([Wh.](http://www.warnemyr.com/skrgram/grammar/roots/root_bandh.html); Bucknell p. 179)
- [guh](http://sanskrit.anshir.ru/forms.php?id=429&final=pr): ghugukṣati vs. jughukṣati/jugukṣati ([Wh.](http://www.warnemyr.com/skrgram/grammar/roots/root_guh.html); Bucknell p. 161)

Ожидается, что такой же баг будет при соблюдении условий переноса при удвоении.

**Comment by anshir-rus** [comment]
Первые три примера решены в сегодняшнем обновлении. После два - баг в теории, потребуются консультации.

**Comment by anshir-rus** [comment]
Добавлен новый параметр для удвоенных корней. Сейчас перенос работает ожидаемо. Пишите, если вдруг новые случаи возникнут.
